components_manager:
    task_processors:                  

        main-task-processor:          
            worker_threads: $worker-threads         

        fs-task-processor:            
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       
        server:
            listener:                 
                port: $server-port            
                task_processor: main-task-processor    
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  
        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        handler-posts:
            path: /api/posts
            method: GET,DELETE,POST
            task_processor: main-task-processor

        database:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor
